/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TaskOverviewPanel.java
 *
 * Created on Sep 16, 2010, 12:26:10 AM
 */

package us.fract.gui;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.jdesktop.swingx.JXBusyLabel;
import org.jdesktop.swingx.JXImagePanel;

/**
 *
 * @author bowenl2
 */
public class TaskOverviewPanel extends javax.swing.JPanel {
    private BufferedImage completedImage;
    private BufferedImage taskImage;
    private JXBusyLabel busyLabel;
    private JXImagePanel completedImagePanel;


    public TaskOverviewPanel(String taskLabelText, String taskImagePath)
            throws IOException {
        this();
        busyLabel = new JXBusyLabel(new Dimension(32, 32));
        busyLabel.setBusy(true);
        taskLabel.setText(taskLabelText);
        completedImage = ImageIO.read(new File(Images.Path.CHECK));
        completedImagePanel = new JXImagePanel();
        completedImagePanel.setImage(completedImage);
        setTaskIcon(taskImagePath);
        setBusyState(true);
    }


    public TaskOverviewPanel() {
        initComponents();
    }

    public void setTaskIcon(String path)
            throws IOException {
        taskImage = ImageIO.read(new File(path));
        imagePanel.setImage(taskImage);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskLabel = new javax.swing.JLabel();
        imagePanel = new org.jdesktop.swingx.JXImagePanel();
        iconPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(32767, 60));
        setMinimumSize(new java.awt.Dimension(0, 60));
        setPreferredSize(new java.awt.Dimension(119, 60));
        setLayout(new java.awt.BorderLayout(10, 10));

        taskLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        taskLabel.setText("[Task]");
        add(taskLabel, java.awt.BorderLayout.CENTER);

        imagePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        imagePanel.setMaximumSize(new java.awt.Dimension(48, 48));
        imagePanel.setMinimumSize(new java.awt.Dimension(48, 48));
        imagePanel.setPreferredSize(new java.awt.Dimension(48, 48));
        add(imagePanel, java.awt.BorderLayout.LINE_START);

        iconPanel.setLayout(new javax.swing.BoxLayout(iconPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(iconPanel, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    public void setBusyState(boolean busy) {
        iconPanel.removeAll();
        iconPanel.add(busy ? busyLabel : completedImagePanel);
        iconPanel.validate();

        imagePanel.setAlpha(busy ? .5F : 1F);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel iconPanel;
    private org.jdesktop.swingx.JXImagePanel imagePanel;
    private javax.swing.JLabel taskLabel;
    // End of variables declaration//GEN-END:variables


}
